@baseUrl = http://localhost:8080

### Listar Todos os Profissionais Ativos (Geral)
GET {{baseUrl}}/alocacoes/profissionais/ativos
Content-Type: application/json

### Listar Todos os Usuarios Ativos (Geral)
GET {{baseUrl}}/alocacoes/usuarios/ativos
Content-Type: application/json

### Listar Equipe de um Projeto Específico (Já vinculados)
GET {{baseUrl}}/alocacoes/projeto/1
Content-Type: application/json

### Vincular Profissionais a um Item
POST {{baseUrl}}/alocacoes/vincular
Content-Type: application/json

{
  "projectId": 1,
  "itemId": 1,
  "professionalIds": [
    "550e8400-e29b-41d4-a716-446655440010",
    "550e8400-e29b-41d4-a716-446655440012"
  ]
}